"use client";

import type { Summary } from "@/lib/types";
import { useToast } from "./Toaster";

export function ExportButtons({ summary }: { summary: Summary }) {
  const toast = useToast();

  async function copyMarkdown() {
    const md = toMarkdown(summary);
    try {
      await navigator.clipboard.writeText(md);
      toast.success("Copied as Markdown.");
    } catch {
      toast.error("Could not copy to clipboard.");
    }
  }

  function downloadBibtex() {
    const bib = toBibtex(summary);
    download(`${slug(summary.paper.title)}.bib`, bib, "application/x-bibtex");
    toast.info("BibTeX downloaded.");
  }

  function downloadMarkdown() {
    const md = toMarkdown(summary);
    download(`${slug(summary.paper.title)}.md`, md, "text/markdown");
    toast.info("Markdown downloaded.");
  }

  return (
    <div className="flex flex-wrap items-center gap-2">
      <button
        type="button"
        onClick={copyMarkdown}
        className="inline-flex items-center gap-1.5 rounded-md border border-slate-300 bg-white px-2.5 py-1 text-xs font-medium text-slate-700 transition hover:border-cyan-500 hover:text-cyan-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:border-cyan-400 dark:hover:text-cyan-300"
      >
        Copy Markdown
      </button>
      <button
        type="button"
        onClick={downloadMarkdown}
        className="inline-flex items-center gap-1.5 rounded-md border border-slate-300 bg-white px-2.5 py-1 text-xs font-medium text-slate-700 transition hover:border-cyan-500 hover:text-cyan-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:border-cyan-400 dark:hover:text-cyan-300"
      >
        Download .md
      </button>
      <button
        type="button"
        onClick={downloadBibtex}
        className="inline-flex items-center gap-1.5 rounded-md border border-slate-300 bg-white px-2.5 py-1 text-xs font-medium text-slate-700 transition hover:border-cyan-500 hover:text-cyan-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:border-cyan-400 dark:hover:text-cyan-300"
      >
        Download .bib
      </button>
    </div>
  );
}

// ─── Formatters ─────────────────────────────────────────────────────

function toMarkdown(s: Summary): string {
  const lines: string[] = [];
  lines.push(`# ${s.paper.title}`);
  lines.push("");
  lines.push(`*${s.paper.authors.join(", ")}* — ${s.paper.venue ?? "arXiv"} ${s.paper.year}`);
  if (s.paper.arxivId) lines.push(`arXiv: \`${s.paper.arxivId}\``);
  if (s.paper.doi) lines.push(`DOI: \`${s.paper.doi}\``);
  if (s.paper.pdfUrl) lines.push(`PDF: ${s.paper.pdfUrl}`);
  lines.push("");

  if (s.paper.abstract) {
    lines.push("## Abstract");
    lines.push("");
    lines.push(s.paper.abstract);
    lines.push("");
  }

  for (const sec of s.sections) {
    lines.push(`## ${sec.heading}`);
    lines.push("");
    for (const b of sec.bullets) lines.push(`- ${b}`);
    lines.push("");
  }

  if (s.keywords && s.keywords.length > 0) {
    lines.push("## Keywords");
    lines.push("");
    lines.push(s.keywords.map((k) => `\`${k}\``).join(", "));
    lines.push("");
  }

  lines.push("---");
  lines.push(`Generated by Research Paper Summarizer · ${new Date(s.createdAt).toLocaleDateString()}`);
  return lines.join("\n");
}

function toBibtex(s: Summary): string {
  const key = bibKey(s);
  const fields: Record<string, string | undefined> = {
    title: `{${escapeBib(s.paper.title)}}`,
    author: s.paper.authors.map((a) => escapeBib(a)).join(" and "),
    year: String(s.paper.year),
    journal: s.paper.venue ? escapeBib(s.paper.venue) : undefined,
    eprint: s.paper.arxivId,
    archivePrefix: s.paper.arxivId ? "arXiv" : undefined,
    doi: s.paper.doi,
    url: s.paper.pdfUrl,
  };
  const body = Object.entries(fields)
    .filter(([, v]) => v !== undefined && v !== "")
    .map(([k, v]) => `  ${k} = {${(v as string).replace(/^[{]|[}]$/g, "")}},`)
    .join("\n");
  return `@article{${key},\n${body}\n}\n`;
}

function bibKey(s: Summary): string {
  const firstAuthor = (s.paper.authors[0] ?? "anon").split(/\s+/).pop() ?? "anon";
  return `${firstAuthor.toLowerCase().replace(/[^a-z0-9]/g, "")}${s.paper.year}`;
}

function escapeBib(s: string): string {
  return s.replace(/[{}]/g, "");
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60);
}

function download(filename: string, content: string, type: string): void {
  const blob = new Blob([content], { type: `${type};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 0);
}
